### ISSUE TITLE
PDS-Book/Chapters/chapter01.Rmd does not show graphics

### ISSUE THREAD

**Issue by mooresk1** [alanarnholt/PDS-Book#1]
I can open this chapter and read the text fine but no graphics. For instance, in Ch1 I see this:

An Introduction to Statistics^[https://oli.cmu.edu/jcourse/workbook/activity/page?context=434b846480020ca6018dda7ea62a2528]

producingdata

If I click on "producing data" I get the 404 "page not found" error. I'm using Chrome. How do I fix this?

**Comment by alanarnholt** [comment]
You need to clone, then compile the parent document using R.  We will cover this Monday....this is also covered in the assigned videos for next week.
